coreruleset/website

config/_default/languages.yaml
i18n/en.yaml

- update first -> 1st
- move up text to form OWASP CRS / PROJECT

chore: update front page

---

assets/scss/_footer.scss
assets/scss/_variables.scss

Changing this to somewhat CRS blueish, it doesn't look good now with the logo:
Will try other variants.

fix: update footer color

---

content/pages/support.md

fix: support broken links

---

layouts/partials/latest-news.html
layouts/partials/sponsors.html

Items look better aligned now, and changed color:

fix: items alignment in home

---

config/_default/languages.yaml

- add link to all blog posts in menu
- add link to docs in menu

fix: add link to posts and docs

---

assets/scss/_variables.scss

Fixes footer menu link hover:
https://github.com/coreruleset/website/assets/3012076/4fc1117b-8a3c-4b1c-a144-c1b1f5cb0d06

fix: menu link hover

---

content/blog/2024-02-27-new-feature-spotlight-early-blocking.md
content/blog/2024-03-27-crs-version-4-1-0-released.md
content/blog/2024-04-04-save-the-date-crs-community-summit-on-june-26-in-lisbon.md

chore: update blog posts

---

config/production/hugo.yaml

chore: update production links

---

content/blog/2024-03-27-crs-version-4-1-0-released.md

typo: Typo fix in blog entry

---

content/blog/2021-12-13-crs-and-log4j-log4shell-cve-2021-44228.md

This should fix url to match wordpress permalink.

fix: update url to match permalink

---

layouts/_default/rss.xml

fix: rss feed from upstream theme

---

content/blog/2017-07-27-crs3-presentation-owasp-london.md
content/blog/2017-11-21-top-5-ways-crs-can-help-you-fight-owasp-top-10.md
content/blog/2017-12-07-core-rule-set-project-winning-osbar-award.md
content/blog/2018-01-12-crs-project-new-january-2018.md
content/blog/2018-02-11-crs-project-news-february-208.md
content/blog/2018-10-03-owasp-crs-slack.md
content/blog/2019-08-26-optimizing-regular-expressions.md
content/blog/2020-12-28-owasp-modsecurity-core-rule-set-v3-3-1-release-candidate-1-available.md
content/blog/2022-01-12-crs-plugin-mechanism.md
content/blog/2022-03-08-crs-names-felipe-zipitria-as-third-co-lead.md
content/blog/2023-01-17-meet-the-crs-team-franzi-the-puzzle-loving-hard-worker-with-a-mission.md
content/blog/2023-05-03-a-brief-report-on-the-crs-community-summit-2023.md

Fixes https://github.com/coreruleset/website/issues/71.

fix: fixing links to blog

---

archetypes/blog.md

- add a new archetype (this is hugo stanza for "template" ;) )
- help onboarding

feat: add new blog post archetype

---

content/blog/2018-09-27-crs-project-news-september-2018.md

While the WaybackMachine does have a copy of the post, the video has not been archived.

chore: remove obsolete link

---

content/blog/2024-08-16-felipe-named-owasps-project-person-of-the-year-2024.md

New blog post on Felipe's WASPY 2024

New blog post

---

renovate.json

- renovate should be running daily.

chore: run renovatebot daily

---

renovate.json

fix: update release

---

.github/workflows/test.yml

- update lychee action
- fix not working configuration

fix: update lychee action config

---

.github/workflows/gh-pages.yml
.github/workflows/test.yml

- update base hugo version
- add tag for future renovatebot updates
- compatibility with new theme version

fix: update hugo version

---

content/blog/2024-10-29-crs-versions-4-8-0-and-3-3-7-released.md

Add draft of release blog post covering the 4.8.0 and 3.3.7 releases.

Add draft of release blog post

---

.github/workflows/test.yml
content/blog/2024-01-11-a-new-silver-sponsor-for-crs-swiss-post.md

Fix link checker errors for websites that require cookies

chore: enable cookes for lychee

---

data/authors.yaml

chore: update avatar image

---

static/_redirects

- add redirect file for simple redirects
- add link to register for community call

feat: add cloudflare pages redirect file

---

static/_redirects

- add redirect to community call

chore: add redirect to community call

---

.github/workflows/gh-pages.yml
.github/workflows/test.yml
package-lock.json
package.json

Hugo 0.146.0 introduces a new templating engine. The Hugo theme we use isn't compatible yet.

fix: downgrade Hugo to 0.145.0
